//! Build-time checked modules and the exact context required to reuse them.
//!
//! The compiler owns graph ordering and feeds this snapshot the same imports
//! at build time and runtime. Source equality and a rebuild provide invalidation;
//! there is no runtime file cache. Host callbacks cannot be captured, so baking
//! declines any check that invokes one, even if it happens to return a type.

use std::cell::Cell;
use std::collections::HashMap;
use std::rc::Rc;
use std::sync::{Arc, OnceLock};

use aven_parser::{Module, ModuleRole};
use serde::de::DeserializeOwned;

use crate::{
    BuiltinMethodEnvironment, CheckOutput, ComptimeArg, ComptimeError, ComptimeModuleIdentity,
    HostComptimeFn, HostComptimeParam, HostGlobals, HostStatics, ModuleImports, Type,
    check_module_with_host_globals_and_imports_in_role,
};

/// Const intern tables plus per-module blobs. Generated by aven-cli's build
/// script and `include!`'d into the binary.
#[derive(Debug, Clone, Copy)]
pub struct BakedStdTables {
    pub hosts: &'static [&'static [u8]],
    pub imports: &'static [&'static [u8]],
    pub methods: &'static [&'static [u8]],
    pub modules: &'static [BakedStdModule],
}

/// One embedded module: unique JSON plus indices into [`BakedStdTables`].
#[derive(Debug, Clone, Copy)]
pub struct BakedStdModule {
    pub specifier: &'static str,
    pub blob: &'static [u8],
    pub host: u16,
    pub imports: u16,
    pub import_methods: u16,
    pub output_methods: u16,
}

/// Bake-time intern result: each distinct snapshot serialized once.
pub struct InternedStdModules {
    pub hosts: Vec<Vec<u8>>,
    pub imports: Vec<Vec<u8>>,
    pub methods: Vec<Vec<u8>>,
    pub modules: Vec<InternedStdModule>,
}

/// One module's slim blob and intern indices, produced by [`intern_std_modules`].
pub struct InternedStdModule {
    pub specifier: String,
    pub blob: Vec<u8>,
    pub host: u16,
    pub imports: u16,
    pub import_methods: u16,
    pub output_methods: u16,
}

/// Runtime loader: interned snapshots decode once per process-owned tables
/// object and are reused by every visited module.
#[derive(Clone)]
pub struct BakedStd {
    tables: &'static BakedStdTables,
    decoded: Arc<DecodedInterns>,
}

impl PartialEq for BakedStd {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self.tables, other.tables)
    }
}

impl Eq for BakedStd {}

impl std::fmt::Debug for BakedStd {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("BakedStd")
            .field("modules", &self.tables.modules.len())
            .finish()
    }
}

struct DecodedInterns {
    hosts: Vec<OnceLock<Arc<HostContext>>>,
    imports: Vec<OnceLock<Arc<ModuleImports>>>,
    methods: Vec<OnceLock<Arc<BuiltinMethodEnvironment>>>,
}

impl BakedStd {
    pub fn new(tables: &'static BakedStdTables) -> Self {
        Self {
            tables,
            decoded: Arc::new(DecodedInterns {
                hosts: tables.hosts.iter().map(|_| OnceLock::new()).collect(),
                imports: tables.imports.iter().map(|_| OnceLock::new()).collect(),
                methods: tables.methods.iter().map(|_| OnceLock::new()).collect(),
            }),
        }
    }

    /// Decode the named module, filling interned host, imports and methods
    /// from the side tables. Missing specifiers yield `None` (fresh check).
    pub fn decode(&self, specifier: &str) -> Option<BakedCheck> {
        let module = self
            .tables
            .modules
            .iter()
            .find(|module| module.specifier == specifier)?;
        let host = interned_arc(&self.decoded.hosts, self.tables.hosts, module.host, "host");
        let import_shell = interned_arc(
            &self.decoded.imports,
            self.tables.imports,
            module.imports,
            "imports",
        );
        let import_methods = interned_arc(
            &self.decoded.methods,
            self.tables.methods,
            module.import_methods,
            "builtin methods",
        );
        let output_methods = interned_arc(
            &self.decoded.methods,
            self.tables.methods,
            module.output_methods,
            "builtin methods",
        );
        let mut baked: BakedCheck = serde_json::from_slice(module.blob)
            .expect("embedded checked module must decode with the matching build schema");
        baked.host = host;
        let mut imports = (*import_shell).clone();
        imports.builtin_methods = (*import_methods).clone();
        baked.imports = Arc::new(imports);
        baked.output.builtin_methods = (*output_methods).clone();
        Some(baked)
    }
}

fn interned_arc<T: DeserializeOwned>(
    slots: &[OnceLock<Arc<T>>],
    blobs: &'static [&'static [u8]],
    index: u16,
    what: &str,
) -> Arc<T> {
    let index = usize::from(index);
    let (slot, bytes) = slots.get(index).zip(blobs.get(index)).unwrap_or_else(|| {
        panic!("interned {what} index {index} must refer to this build's intern table")
    });
    Arc::clone(slot.get_or_init(|| {
        Arc::new(serde_json::from_slice(bytes).unwrap_or_else(|error| {
            panic!("embedded interned {what} must decode with the matching build schema: {error}")
        }))
    }))
}

/// Intern host, import shells and builtin-method environments by value so
/// equal snapshots are stored once. HashMap JSON encodings of equal values
/// are not byte-identical; comparison is [`PartialEq`], then each distinct
/// value is serialized once.
pub fn intern_std_modules(
    modules: &[(String, BakedCheck)],
) -> Result<InternedStdModules, serde_json::Error> {
    let mut hosts: Vec<&HostContext> = Vec::new();
    let mut methods: Vec<&BuiltinMethodEnvironment> = Vec::new();
    let mut shells: Vec<ModuleImports> = Vec::new();
    let mut interned = Vec::with_capacity(modules.len());
    for (specifier, checked) in modules {
        let host = intern_ref(&mut hosts, checked.host.as_ref());
        let import_methods = intern_ref(&mut methods, &checked.imports.builtin_methods);
        let output_methods = intern_ref(&mut methods, &checked.output.builtin_methods);
        let mut shell = (*checked.imports).clone();
        shell.builtin_methods = BuiltinMethodEnvironment::default();
        let imports = intern_owned(&mut shells, shell);
        interned.push(InternedStdModule {
            specifier: specifier.clone(),
            blob: serde_json::to_vec(checked)?,
            host,
            imports,
            import_methods,
            output_methods,
        });
    }
    Ok(InternedStdModules {
        hosts: hosts
            .iter()
            .map(serde_json::to_vec)
            .collect::<Result<_, _>>()?,
        imports: shells
            .iter()
            .map(serde_json::to_vec)
            .collect::<Result<_, _>>()?,
        methods: methods
            .iter()
            .map(serde_json::to_vec)
            .collect::<Result<_, _>>()?,
        modules: interned,
    })
}

fn intern_ref<'a, T: PartialEq>(table: &mut Vec<&'a T>, value: &'a T) -> u16 {
    if let Some(index) = table.iter().position(|entry| *entry == value) {
        intern_u16(index)
    } else {
        let index = table.len();
        table.push(value);
        intern_u16(index)
    }
}

fn intern_owned<T: PartialEq>(table: &mut Vec<T>, value: T) -> u16 {
    if let Some(index) = table.iter().position(|entry| *entry == value) {
        intern_u16(index)
    } else {
        let index = table.len();
        table.push(value);
        intern_u16(index)
    }
}

fn intern_u16(index: usize) -> u16 {
    u16::try_from(index).expect("baked intern table fits in u16")
}

#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
struct HostContext {
    types: Vec<(String, Type)>,
    type_definitions: Vec<(String, Type)>,
    statics: HostStatics,
    comptime_params: HashMap<String, Vec<HostComptimeParam>>,
    type_definition_module: ComptimeModuleIdentity,
}

impl HostContext {
    fn new(globals: &HostGlobals) -> Self {
        Self {
            types: globals.types.clone(),
            type_definitions: globals.type_definitions.clone(),
            statics: globals.statics.clone(),
            comptime_params: globals
                .comptime_fns
                .iter()
                .map(|(name, spec)| (name.clone(), spec.comptime_params.clone()))
                .collect(),
            type_definition_module: globals.type_definition_module.clone(),
        }
    }

    fn matches(&self, globals: &HostGlobals) -> bool {
        self.types == globals.types
            && self.type_definitions == globals.type_definitions
            && self.statics == globals.statics
            && self.type_definition_module == globals.type_definition_module
            && comptime_params_match(&self.comptime_params, globals)
    }
}

fn comptime_params_match(
    baked: &HashMap<String, Vec<HostComptimeParam>>,
    globals: &HostGlobals,
) -> bool {
    // Registration order on the run host need not match bake-time HashMap
    // insertion order. Zip-equality missed every module under `aven run`.
    let runtime: HashMap<&str, _> = globals
        .comptime_fns
        .iter()
        .map(|(name, spec)| (name.as_str(), &spec.comptime_params))
        .collect();
    let baked: HashMap<&str, _> = baked
        .iter()
        .map(|(name, params)| (name.as_str(), params))
        .collect();
    baked == runtime
}

/// A checked module with its complete, comparable checking inputs.
///
/// Serialize only artifacts produced by [`Self::check`]. The format is internal
/// to one build and must never be accepted from a runtime cache or untrusted
/// input. Recursive type identities are re-interned by semantic key on decode.
/// Host, imports and `output.builtin_methods` live in intern tables; module
/// JSON omits them and [`BakedStd::decode`] fills them from those tables.
/// Guard comparison is still value equality of the assembled snapshots.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct BakedCheck {
    source: String,
    /// Equal source bytes do not determine equal syntax: a custom operator
    /// table changes how an entry module's infix chain associates, and so what
    /// the checker sees. The fingerprint of the table the module was parsed
    /// with is therefore a checking input like any other.
    fixity_fingerprint: String,
    #[serde(default, skip_serializing)]
    host: Arc<HostContext>,
    #[serde(default, skip_serializing)]
    imports: Arc<ModuleImports>,
    identity: ComptimeModuleIdentity,
    role: ModuleRole,
    output: CheckOutput,
}

impl BakedCheck {
    /// Check with callback sentinels. Equal types and callback parameter specs
    /// determine the same execution until a resolver is invoked; if no resolver
    /// was invoked, its implementation cannot have influenced the result.
    pub fn check(
        source: &str,
        fixity_fingerprint: &str,
        module: &Module,
        globals: &HostGlobals,
        imports: &ModuleImports,
        identity: ComptimeModuleIdentity,
        role: ModuleRole,
    ) -> Option<Self> {
        let invoked = Rc::new(Cell::new(false));
        let mut guarded_globals = globals.clone();
        for (_, spec) in &mut guarded_globals.comptime_fns {
            spec.resolver = Rc::new(CallbackSentinel(Rc::clone(&invoked)));
        }
        let output = check_module_with_host_globals_and_imports_in_role(
            module,
            &guarded_globals,
            imports,
            identity.clone(),
            role,
        );
        (!invoked.get()).then(|| Self {
            source: source.to_owned(),
            fixity_fingerprint: fixity_fingerprint.to_owned(),
            host: Arc::new(HostContext::new(globals)),
            imports: Arc::new(imports.clone()),
            identity,
            role,
            output,
        })
    }

    /// Consume this artifact only if every checking input matches. A custom
    /// host, prelude, ambient environment, module role or source falls back to
    /// ordinary checking. No best-effort or partial interface reuse is sound.
    pub fn into_checked(
        self,
        source: &str,
        fixity_fingerprint: &str,
        globals: &HostGlobals,
        imports: &ModuleImports,
        identity: &ComptimeModuleIdentity,
        role: ModuleRole,
    ) -> Option<CheckOutput> {
        (self.source == source
            && self.fixity_fingerprint == fixity_fingerprint
            && self.host.matches(globals)
            && *self.imports == *imports
            && self.identity == *identity
            && self.role == role)
            .then_some(self.output)
    }
}

struct CallbackSentinel(Rc<Cell<bool>>);

impl HostComptimeFn for CallbackSentinel {
    fn resolve(&self, _args: &[ComptimeArg]) -> Result<Type, ComptimeError> {
        self.0.set(true);
        Err(ComptimeError::new("host callback cannot be baked"))
    }
}

// JSON object keys cannot represent spans or semantic recursive type keys.
// Sequence entries preserve those keys without a second wire representation.
pub(crate) mod map_entries {
    use super::HashMap;
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use std::hash::Hash;

    pub fn serialize<K: Serialize, V: Serialize, S: Serializer>(
        map: &HashMap<K, V>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        map.iter().collect::<Vec<_>>().serialize(serializer)
    }

    pub fn deserialize<
        'de,
        K: Deserialize<'de> + Eq + Hash,
        V: Deserialize<'de>,
        D: Deserializer<'de>,
    >(
        deserializer: D,
    ) -> Result<HashMap<K, V>, D::Error> {
        Ok(Vec::<(K, V)>::deserialize(deserializer)?
            .into_iter()
            .collect())
    }
}

pub(crate) mod integer {
    use aven_core::Int;
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(value: &Int, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_str(value)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Int, D::Error> {
        String::deserialize(deserializer)?
            .parse()
            .map_err(serde::de::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{HostComptimeFnSpec, build};
    use aven_parser::parse_module;

    /// Every module in these tests is parsed with the default operator
    /// table, so they all share its fingerprint.
    const FIXITY: &str = "";

    #[test]
    fn checked_output_matches_fresh_and_rejects_context_changes() {
        // A same-source snapshot must not hide host-dependent type errors or
        // accept a different ambient/prelude/import environment.
        let source = "value: Text = external\n{ value }\n";
        let module = parse_module(source).module;
        let globals = HostGlobals::types_only(&[("external".into(), build::text())]);
        let imports = ModuleImports::default();
        let identity = ComptimeModuleIdentity::specifier("test");
        let baked = BakedCheck::check(
            source,
            FIXITY,
            &module,
            &globals,
            &imports,
            identity.clone(),
            ModuleRole::Dependency,
        )
        .expect("module never calls a host callback");
        let fresh = check_module_with_host_globals_and_imports_in_role(
            &module,
            &globals,
            &imports,
            identity.clone(),
            ModuleRole::Dependency,
        );
        assert_eq!(
            baked.clone().into_checked(
                source,
                FIXITY,
                &globals,
                &imports,
                &identity,
                ModuleRole::Dependency
            ),
            Some(fresh)
        );
        let different = HostGlobals::types_only(&[("external".into(), build::int())]);
        assert!(
            baked
                .clone()
                .into_checked(
                    source,
                    FIXITY,
                    &different,
                    &imports,
                    &identity,
                    ModuleRole::Dependency
                )
                .is_none()
        );
        let mut different = imports.clone();
        different.insert("other", build::int());
        assert!(
            baked
                .clone()
                .into_checked(
                    source,
                    FIXITY,
                    &globals,
                    &different,
                    &identity,
                    ModuleRole::Dependency
                )
                .is_none()
        );
        let mut different = imports.clone();
        different.set_trusted_builtin_method_source(true);
        assert!(
            baked
                .clone()
                .into_checked(
                    source,
                    FIXITY,
                    &globals,
                    &different,
                    &identity,
                    ModuleRole::Dependency
                )
                .is_none()
        );
        assert!(
            baked
                .clone()
                .into_checked(
                    "{ value: 1 }",
                    FIXITY,
                    &globals,
                    &imports,
                    &identity,
                    ModuleRole::Dependency
                )
                .is_none()
        );
        assert!(
            baked
                .clone()
                .into_checked(
                    source,
                    FIXITY,
                    &globals,
                    &imports,
                    &identity,
                    ModuleRole::Entry
                )
                .is_none()
        );
        // Same bytes, different operator table: an entry module's infix chain
        // associates differently, so this is a different module to check.
        assert!(
            baked
                .clone()
                .into_checked(
                    source,
                    "custom-fixities",
                    &globals,
                    &imports,
                    &identity,
                    ModuleRole::Dependency
                )
                .is_none()
        );
        assert!(
            baked
                .into_checked(
                    source,
                    FIXITY,
                    &globals,
                    &imports,
                    &ComptimeModuleIdentity::Current,
                    ModuleRole::Dependency
                )
                .is_none()
        );
    }

    struct UnexpectedCallback;

    impl HostComptimeFn for UnexpectedCallback {
        fn resolve(&self, _args: &[ComptimeArg]) -> Result<Type, ComptimeError> {
            panic!("baking must never execute a host callback");
        }
    }

    #[test]
    fn callback_dependent_modules_are_not_baked() {
        // Equal host signatures cannot establish equal callback behavior.
        let globals = HostGlobals::new(
            vec![(
                "lookup".into(),
                build::function(vec![build::text()], build::text()),
            )],
            vec![(
                "lookup".into(),
                HostComptimeFnSpec::new(Rc::new(UnexpectedCallback), vec![0]),
            )],
        );
        let source = "value = lookup(\"key\")\n{ value }\n";
        assert!(
            BakedCheck::check(
                source,
                FIXITY,
                &parse_module(source).module,
                &globals,
                &ModuleImports::default(),
                ComptimeModuleIdentity::Current,
                ModuleRole::Entry
            )
            .is_none()
        );
    }

    #[test]
    fn comptime_params_match_independent_of_registration_order() {
        // `aven run` registers host comptime functions in a different Vec
        // order than bake-time `standard_check_host_globals`. Zip-equality
        // against HashMap iteration missed every baked module on that path.
        struct Unused;
        impl HostComptimeFn for Unused {
            fn resolve(&self, _args: &[ComptimeArg]) -> Result<Type, ComptimeError> {
                panic!("unused callback");
            }
        }
        let globals = HostGlobals::new(
            vec![],
            vec![
                (
                    "first".into(),
                    HostComptimeFnSpec::new(Rc::new(Unused), vec![0]),
                ),
                (
                    "second".into(),
                    HostComptimeFnSpec::new(Rc::new(Unused), vec![1]),
                ),
            ],
        );
        let source = "{ 1 }\n";
        let baked = BakedCheck::check(
            source,
            FIXITY,
            &parse_module(source).module,
            &globals,
            &ModuleImports::default(),
            ComptimeModuleIdentity::specifier("test"),
            ModuleRole::Dependency,
        )
        .expect("module never calls a host callback");
        let mut reversed = globals.clone();
        reversed.comptime_fns.reverse();
        // Both orders, against clones of one artifact. Testing only the
        // reversed vector would let the original zip comparison pass whenever
        // the baked HashMap happened to iterate in that same order; an
        // order-sensitive comparison has to reject one of these two.
        for (label, candidate) in [("registered", &globals), ("reversed", &reversed)] {
            assert!(
                baked
                    .clone()
                    .into_checked(
                        source,
                        FIXITY,
                        candidate,
                        &ModuleImports::default(),
                        &ComptimeModuleIdentity::specifier("test"),
                        ModuleRole::Dependency,
                    )
                    .is_some(),
                "{label} order must match the same baked artifact"
            );
        }
        // Order is not significant; the params themselves still are.
        let mut respecified = globals.clone();
        respecified.comptime_fns[1].1 = HostComptimeFnSpec::new(Rc::new(Unused), vec![0]);
        assert!(
            baked
                .into_checked(
                    source,
                    FIXITY,
                    &respecified,
                    &ModuleImports::default(),
                    &ComptimeModuleIdentity::specifier("test"),
                    ModuleRole::Dependency,
                )
                .is_none()
        );
    }
}
